<a href="https://colab.research.google.com/github/ricardosimplicio/PUC-Rio-MVP-Analise_de_dados_e_Boas_Praticas/blob/main/Reprodu%C3%A7%C3%A3o_Aula_2_Iris_RS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Aula 03  - Pré-Processametno de Dados

## Baixando os pacotes do Scikit-learn

In [ ]:
# importação de pacotes
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler #normalização
from sklearn.preprocessing import StandardScaler #padronização
from sklearn.preprocessing import OrdinalEncoder # ordinal encoding
from sklearn.preprocessing import OneHotEncoder # ond-hot enconding e dummy enconding

##Limpeza - Tratsametno de Missing

In [ ]:
#importante dados da uma url para um dataframe

#url a importar
url_dados = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

#label dos atributos do dataset
labels_atributos = ['comprimento_sepala', 'largura_sepala', 'comprimento_petala', 'largura_petala', 'especie' ]

# carga do dataset através da url
iris = pd.read_csv(url_dados, names = labels_atributos)

#exibindo as últimas linhas
iris.tail()



comprimento_sepala  largura_sepala  comprimento_petala  largura_petala  \
145                 6.7             3.0                 5.2             2.3   
146                 6.3             2.5                 5.0             1.9   
147                 6.5             3.0                 5.2             2.0   
148                 6.2             3.4                 5.4             2.3   
149                 5.9             3.0                 5.1             1.8   

            especie  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica

In [ ]:
#criando um novo dataframe com o iris + uma nova linhas com um valor missing para o próximo exemplo

new_row = {'largura_sepala': 4.0,
          'comprimento_petala': 5.0,
          'largura_petala': 0.4,
          'especie': 'Iris-setosa',
          'comprimento_sepala': None}

df = pd.concat([iris, pd.DataFrame([new_row])], ignore_index = True)

df.tail()

<ipython-input-14-45ead2ff596f>:9: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([iris, pd.DataFrame([new_row])], ignore_index = True)


comprimento_sepala  largura_sepala  comprimento_petala  largura_petala  \
146                 6.3             2.5                 5.0             1.9   
147                 6.5             3.0                 5.2             2.0   
148                 6.2             3.4                 5.4             2.3   
149                 5.9             3.0                 5.1             1.8   
150                 NaN             4.0                 5.0             0.4   

            especie  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  
150     Iris-setosa

In [ ]:
#eliminando linhas que tenham algum valor missing

df = df.dropna(how='any')
df.tail()

comprimento_sepala  largura_sepala  comprimento_petala  largura_petala  \
145                 6.7             3.0                 5.2             2.3   
146                 6.3             2.5                 5.0             1.9   
147                 6.5             3.0                 5.2             2.0   
148                 6.2             3.4                 5.4             2.3   
149                 5.9             3.0                 5.1             1.8   

            especie  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica

In [ ]:
#criando  (novamente) um novo datafram com iris + uma nova linhas com um valor missing para o príoximo exemplo

new_row = {'largura_sepala': 4.0,
          'comprimento_petala': 5.0,
          'largura_petala': 0.4,
          'especie': 'Iris-setosa',
          'comprimento_sepala': None}

df = pd.concat([iris, pd.DataFrame([new_row])], ignore_index = True)

df.tail()


<ipython-input-16-4df594d962c4>:9: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([iris, pd.DataFrame([new_row])], ignore_index = True)


comprimento_sepala  largura_sepala  comprimento_petala  largura_petala  \
146                 6.3             2.5                 5.0             1.9   
147                 6.5             3.0                 5.2             2.0   
148                 6.2             3.4                 5.4             2.3   
149                 5.9             3.0                 5.1             1.8   
150                 NaN             4.0                 5.0             0.4   

            especie  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  
150     Iris-setosa

In [ ]:
#eliminando linhas que tenham todos os valores missing

df = df.dropna(how = 'all')
df.tail()


comprimento_sepala  largura_sepala  comprimento_petala  largura_petala  \
146                 6.3             2.5                 5.0             1.9   
147                 6.5             3.0                 5.2             2.0   
148                 6.2             3.4                 5.4             2.3   
149                 5.9             3.0                 5.1             1.8   
150                 NaN             4.0                 5.0             0.4   

            especie  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  
150     Iris-setosa

In [ ]:
#definindo valores para o preenchimento de missing

values = {'comprimento_sepala': iris['comprimento_sepala'].median(),
          'largura_sepala': 5.0,
          'comprimento_petala': 4.0,
          'largura_petala': 0.1,
          'especie':'Iris-setosa'}

# fazendo o preencimento
df = df.fillna(value = values)
df.tail()

comprimento_sepala  largura_sepala  comprimento_petala  largura_petala  \
146                 6.3             2.5                 5.0             1.9   
147                 6.5             3.0                 5.2             2.0   
148                 6.2             3.4                 5.4             2.3   
149                 5.9             3.0                 5.1             1.8   
150                 5.8             4.0                 5.0             0.4   

            especie  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  
150     Iris-setosa

## Transformações  Númericas



In [ ]:
# dados que iremos usar nos exemplos
data = np.asarray([[100, 0.001],
                   [8, 0.05],
                   [50, 0.005],
                   [88, 0.07],
                   [4, 0.1]])
print(data)

[[1.0e+02 1.0e-03]
 [8.0e+00 5.0e-02]
 [5.0e+01 5.0e-03]
 [8.8e+01 7.0e-02]
 [4.0e+00 1.0e-01]]


##Normalização
y = (x -min) / (max- min)

In [ ]:
# Normalização

# definindo o transformador como mim max escaler

scaler = MinMaxScaler()

#transformando  os dados
scaled = scaler.fit_transform(data)
print(scaled)

[[1.         0.        ]
 [0.04166667 0.49494949]
 [0.47916667 0.04040404]
 [0.875      0.6969697 ]
 [0.         1.        ]]


##Padronização
média = soma (x) / contagem (x)

desvio_ padrão = sqrt (soma ((x - média) ^ 2) / contagem (x))

y = (x - média) / desvio padrão


In [ ]:
#Padronização

#definindo o transformador como standard scaler
scaler = StandardScaler()

#transformando os dados
scaled = scaler.fit_transform(data)
print(scaled)

[[ 1.26398112 -1.16389967]
 [-1.06174414  0.12639634]
 [ 0.         -1.05856939]
 [ 0.96062565  0.65304778]
 [-1.16286263  1.44302493]]


##Tranformações Categóricas

one hot enconding e dummy enconding

In [ ]:
#dados que ieramosuesar nos exmeplos

data = np.asarray([['castanhos'], ['verdes'], ['azuis'], ['azuis'], ['castanhos'], ['azuis']])
print(data)

[['castanhos']
 ['verdes']
 ['azuis']
 ['azuis']
 ['castanhos']
 ['azuis']]


## One hot enconding

In [ ]:
#definidndo o transformador com one hot enconding
encoder = OneHotEncoder(sparse = False)

#transformando os dados

onehot = encoder.fit_transform(data)
print(onehot)

[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]]


/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:975: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


## Dummy Variable Encoding

In [ ]:
#definindo o transformado como one hot encoding (com Dummy variable encoder)
encoder = OneHotEncoder(drop= 'first', sparse = False)

#transformamdo os dados
dummy = encoder.fit_transform(data)
print(dummy)

[[1. 0.]
 [0. 1.]
 [0. 0.]
 [0. 0.]
 [1. 0.]
 [0. 0.]]


/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:975: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


# im